export default {
  data () {
    return {
      tokenDetails: [
        {
          name: 'SimpleERC20',
          version: '4.0.0',
          standard: true,
          verified: true,
          detailed: true,
          customizeDecimals: false,
          supplyType: 'Fixed',
          accessType: 'None',
          transferType: 'Unstoppable',
          mintable: false,
          burnable: false,
          erc1363: false,
          tokenRecover: false,
          removeCopyright: false,
          originalPrice: 0,
          price: 0,
          gas: 20,
        },
        {
          name: 'StandardERC20',
          version: '4.0.1',
          standard: true,
          verified: true,
          detailed: true,
          customizeDecimals: true,
          supplyType: 'Fixed',
          accessType: 'None',
          transferType: 'Unstoppable',
          mintable: false,
          burnable: false,
          erc1363: false,
          tokenRecover: false,
          removeCopyright: true,
          originalPrice: 0.15,
          price: 0.002,
          gas: 50,
        },
        {
          name: 'BurnableERC20',
          version: '4.2.0',
          standard: true,
          verified: true,
          detailed: true,
          customizeDecimals: true,
          supplyType: 'Fixed',
          accessType: 'None',
          transferType: 'Unstoppable',
          mintable: false,
          burnable: true,
          erc1363: false,
          tokenRecover: false,
          removeCopyright: true,
          originalPrice: 0.20,
          price: 0.006,
          gas: 100,
        },
        {
          name: 'MintableERC20',
          version: '4.5.0',
          standard: true,
          verified: true,
          detailed: true,
          customizeDecimals: true,
          supplyType: 'Capped',
          accessType: 'Ownable',
          transferType: 'Unstoppable',
          mintable: true,
          burnable: false,
          erc1363: false,
          tokenRecover: false,
          removeCopyright: true,
          originalPrice: 0.25,
          price: 0.01,
          gas: 150,
        },
        {
          name: 'PausableERC20',
          version: '4.6.0',
          standard: true,
          verified: true,
          detailed: true,
          customizeDecimals: true,
          supplyType: 'Fixed',
          accessType: 'Ownable',
          transferType: 'Pausable',
          mintable: false,
          burnable: false,
          erc1363: false,
          tokenRecover: false,
          removeCopyright: true,
          originalPrice: 0.30,
          price: 0.02,
          gas: 250,
        },
        {
          name: 'CommonERC20',
          version: '4.0.1',
          standard: true,
          verified: true,
          detailed: true,
          customizeDecimals: true,
          supplyType: 'Capped',
          accessType: 'Ownable',
          transferType: 'Unstoppable',
          mintable: true,
          burnable: true,
          erc1363: false,
          tokenRecover: false,
          removeCopyright: true,
          originalPrice: 0.35,
          price: 0.03,
          gas: 350,
        },
        {
          name: 'UnlimitedERC20',
          version: '4.4.0',
          standard: true,
          verified: true,
          detailed: true,
          customizeDecimals: true,
          supplyType: 'Unlimited',
          accessType: 'Role Based',
          transferType: 'Unstoppable',
          mintable: true,
          burnable: true,
          erc1363: false,
          tokenRecover: false,
          removeCopyright: true,
          originalPrice: 0.45,
          price: 0.04,
          gas: 500,
        },
        {
          name: 'AmazingERC20',
          version: '4.4.0',
          standard: true,
          verified: true,
          detailed: true,
          customizeDecimals: true,
          supplyType: 'Unlimited',
          accessType: 'Ownable',
          transferType: 'Unstoppable',
          mintable: true,
          burnable: true,
          erc1363: true,
          tokenRecover: true,
          removeCopyright: true,
          originalPrice: 0.85,
          price: 0.05,
          gas: 500,
        },
        {
          name: 'PowerfulERC20',
          version: '4.3.0',
          standard: true,
          verified: true,
          detailed: true,
          customizeDecimals: true,
          supplyType: 'Capped',
          accessType: 'Role Based',
          transferType: 'Unstoppable',
          mintable: true,
          burnable: true,
          erc1363: true,
          tokenRecover: true,
          removeCopyright: true,
          originalPrice: 0.95,
          price: 0.06,
          gas: 600,
        },
      ],
    };
  },
};
